// Product-authored symbolic crosswalk. These votes describe visual styling, not anatomy.
// No forecast score, event probability or biological measurement is produced here.
export type SymbolKey = 'mercury'|'saturn'|'jupiter'|'venus'|'mars'|'moon'|'uranus'|'neptune'|'pluto'|'sun'
export type TraitKey = 'age_impression'|'relative_age'|'height_band'|'body_build'|'proportions'|'face_shape_primary'|'face_shape_secondary'|'jaw'|'eyes_shape'|'eyes_size'|'eye_impression'|'eyelid_style'|'brows'|'nose_bridge'|'nose_shape'|'mouth'|'smile'|'facial_softness'|'hair'|'grooming'|'fashion'|'first_impression'|'closer_impression'|'overall_vibe'|'animal_type_primary'|'animal_type_secondary'
export type Choice = {id:string;ko:string;en:string;symbols:Partial<Record<SymbolKey,number>>}
const c=(id:string,ko:string,en:string,symbols:Choice['symbols']):Choice=>({id,ko,en,symbols})
export const TRAIT_RULES: Partial<Record<TraitKey,Choice[]>> = {
 age_impression:[c('youthful','가볍고 생동감 있는 연령감','youthful and animated adult impression',{mercury:3,uranus:1}),c('balanced','차분함과 생기가 균형 잡힌 연령감','balanced adult presence',{venus:2,moon:1,sun:1}),c('mature','절제되고 성숙한 연령감','restrained mature adult impression',{saturn:3,pluto:1})],
 height_band:[c('tall','평균 이상~큰 키로 보이는 연출','above-average to tall-looking silhouette',{jupiter:3,uranus:1}),c('long','실제 키보다 길어 보이는 비율','elongated visual proportions rather than a measured height',{saturn:2,mercury:1}),c('average','중간 키 느낌의 균형 잡힌 연출','average-looking balanced height',{venus:2,moon:1,mars:1})],
 body_build:[c('slim','슬림~보통','slim to average build',{mercury:2,venus:1,neptune:1}),c('lean','마르고 탄력 있는 선','lean build',{saturn:3,uranus:1}),c('athletic','보통~탄탄한 체형','average to athletic build',{mars:3,sun:1}),c('solid','보통~골격감 있는 체형','average to solid build',{jupiter:2,pluto:1}),c('soft','부드러운 보통 체형','soft average build',{moon:3,venus:1})],
 proportions:[c('long','팔다리가 길어 보이는 비율','long-looking limbs',{jupiter:3,saturn:2,uranus:1}),c('light','가벼운 골격과 좁음~보통 어깨','light frame with narrow to medium shoulders',{mercury:3,neptune:1}),c('balanced','상하체가 균형 잡힌 비율','balanced upper and lower body proportions',{venus:3,moon:1}),c('strong','어깨와 움직임이 또렷한 실루엣','defined shoulder line and active posture',{mars:3,sun:1})],
 face_shape_primary:[c('long_oval','긴 계란형','long oval face',{jupiter:2,mercury:2,saturn:1}),c('soft_oval','부드러운 계란형','soft oval face',{venus:2,neptune:2}),c('angular','각이 분명한 윤곽','defined angular face',{saturn:2,mars:2,pluto:1}),c('round','둥글고 부드러운 윤곽','round-soft facial contour',{moon:3,venus:1}),c('tapered','턱으로 갈수록 가늘어지는 윤곽','gently tapered face',{uranus:2,mercury:2})],
 jaw:[c('soft','둥글게 이어지는 턱선','softly rounded jawline',{moon:2,venus:2,neptune:1}),c('defined','과장 없이 정돈된 각','gently defined jaw, not sculpted',{saturn:2,mars:2}),c('narrow','가볍고 가는 턱선','light narrow jawline',{mercury:2,uranus:1})],
 eyes_shape:[c('long','가로로 길고 바깥쪽이 살짝 올라간 눈매','horizontally elongated eyes with slightly raised outer corners',{mercury:2,mars:1,uranus:1}),c('neutral','길이와 기울기가 균형 잡힌 눈매','balanced eye length with neutral corners',{venus:3,saturn:1}),c('soft','둥근 곡선과 살짝 내려오는 눈꼬리','softly curved eyes with slightly downturned outer corners',{moon:2,neptune:2}),c('deep','길고 깊이감 있는 눈매','long, subtly deep-set eyes',{saturn:2,pluto:2})],
 eyes_size:[c('narrow','세로 크기보다 가로 길이감','moderate vertical openness, length more prominent than size',{mercury:2,saturn:2}),c('moderate','과장 없이 중간 크기','moderately open eyes, not enlarged',{venus:2,mars:1,uranus:1}),c('open','둥글게 열리는 시선','naturally rounded eye openness',{moon:2,jupiter:1,neptune:1})],
 eye_impression:[c('calm','차분하고 절제된 시선','calm restrained gaze',{saturn:2,venus:1}),c('lively','표정에 따라 생동하는 시선','lively expressive gaze',{mercury:2,mars:1,sun:1}),c('dreamy','부드럽고 몽환적인 시선','soft dreamy gaze',{neptune:3,moon:1}),c('focused','선명하고 집중력 있는 시선','focused intense gaze',{pluto:2,mars:2})],
 eyelid_style:[c('inner','속쌍·얕은 쌍꺼풀 계열의 시각적 연출','subtle inner-double or shallow eyelid creases as visual styling',{mercury:2,venus:1,saturn:1}),c('mono','무쌍 계열의 담백한 시각적 연출','monolid visual styling',{saturn:2,mars:1,uranus:1}),c('double','자연스럽게 보이는 쌍꺼풀 계열의 연출','naturally visible double eyelid styling',{moon:2,neptune:1,jupiter:1})],
 brows:[c('straight','자연스럽고 곧은 눈썹','natural straight brows',{saturn:2,mercury:1}),c('arched','부드럽게 휘는 눈썹','gently arched brows',{venus:2,moon:1,neptune:1}),c('defined','결이 또렷한 눈썹','defined natural brow texture',{mars:2,pluto:1,sun:1})],
 nose_bridge:[c('straight','곧고 과장되지 않은 콧대','straight bridge without exaggerated height',{saturn:2,venus:1,mars:1}),c('soft','부드럽게 이어지는 콧대','softly contoured nose bridge',{moon:2,neptune:2}),c('slender','가늘고 정돈된 콧대','slender orderly bridge',{mercury:2,uranus:1})],
 nose_shape:[c('long','옆선이 비교적 긴 코','slightly longer nose profile',{jupiter:2,saturn:1}),c('compact','작고 단정한 코끝','compact natural nose tip',{mercury:2,moon:1}),c('balanced','콧대와 코끝이 균형 잡힌 형태','balanced bridge and tip',{venus:2,mars:1,neptune:1})],
 mouth:[c('restrained','입술선이 차분하고 정돈됨','restrained tidy mouth line',{saturn:2,pluto:1}),c('expressive','말할 때 표정이 살아나는 입매','animated expressive mouth',{mercury:2,mars:1,sun:1}),c('soft','부드럽고 볼륨이 약간 있는 입매','soft subtly fuller lips',{venus:2,moon:1,neptune:1})],
 smile:[c('warm','웃을 때 인상이 부드러워짐','warm smile that softens the face',{venus:2,moon:2}),c('playful','장난기와 생기가 드러나는 미소','playful animated smile',{mercury:2,mars:1,uranus:1}),c('reserved','크지 않지만 눈에 남는 미소','small reserved smile',{saturn:2,pluto:1}),c('open','편안하고 시원하게 웃는 인상','open relaxed smile',{jupiter:2,sun:2})],
 facial_softness:[c('soft','볼과 표정의 곡선이 부드러움','soft cheek contours',{moon:2,venus:1,neptune:1}),c('lean','볼선이 가볍고 골격이 은근히 보임','lean cheeks with subtle bone definition',{saturn:2,mercury:1}),c('defined','볼과 턱의 경계가 또렷함','defined cheek and jaw transitions',{mars:2,pluto:1})],
 hair:[c('relaxed','결이 자연스럽게 흐르는 헤어','naturally flowing hair texture',{venus:2,neptune:1,moon:1}),c('textured','가볍게 흐트러진 결','lightly tousled hair texture',{mercury:2,mars:1}),c('neat','선을 정돈한 단정한 헤어','neatly shaped hair',{saturn:2,sun:1}),c('distinct','한 부분에 변화를 준 개성 있는 헤어','one distinctive detail in the hairstyle',{uranus:3,pluto:1})],
 grooming:[c('polished','과하지 않게 잘 정돈된 인상','subtly polished grooming',{venus:2,saturn:1}),c('easy','힘을 뺀 자연스러운 손질','relaxed everyday grooming',{mercury:1,moon:1,neptune:1,jupiter:1}),c('clean','활동에 맞게 깔끔한 손질','clean practical grooming',{mars:2,sun:1})],
 fashion:[c('minimal','미니멀·깔끔한 핏·무채색','minimal neutral clothing with a clean fit',{venus:2,saturn:2}),c('casual','가볍고 활동적인 캐주얼','light active casual clothing',{mercury:2,mars:2}),c('relaxed','여유 있는 핏과 편안한 소재','relaxed fit and comfortable fabrics',{jupiter:2,moon:1}),c('distinct','단정한 옷에 개성 있는 포인트','one unconventional accent on simple clothing',{uranus:3,pluto:1}),c('soft','부드러운 소재와 은은한 색','soft fabric and muted colors',{neptune:2,moon:1})],
 first_impression:[c('quiet','조용하고 깔끔한 첫인상','quiet tidy first impression',{saturn:2,venus:1}),c('approachable','말을 걸기 편안한 첫인상','approachable first impression',{moon:2,venus:1,jupiter:1}),c('bright','가볍고 활기 있는 첫인상','bright animated first impression',{mercury:2,mars:1,sun:1}),c('distinct','시선이 머무는 독특한 첫인상','distinctive first impression',{uranus:2,pluto:1,neptune:1})],
 closer_impression:[c('playful','표정이 풀리면 장난기가 드러나는 분위기','playfulness as expressions relax',{mercury:2,mars:1,uranus:1}),c('warm','가까이서 더 부드럽게 느껴지는 분위기','a warmer softer visual presence up close',{venus:2,moon:2,neptune:1}),c('steady','차분하고 일관된 분위기','calm composed visual presence',{saturn:2,pluto:1}),c('open','표정과 몸짓이 넉넉하게 느껴짐','open expressions and expansive gestures',{jupiter:2,sun:1})],
 overall_vibe:[c('light','가볍고 생동하는 분위기','light animated overall vibe',{mercury:3,uranus:1}),c('structured','절제된 선과 차분한 분위기','restrained structured overall vibe',{saturn:3,pluto:1}),c('warm','부드럽고 정돈된 분위기','soft balanced overall vibe',{venus:2,moon:2}),c('expansive','시원하고 여유 있는 분위기','open expansive overall vibe',{jupiter:3,sun:1}),c('sharp','선명하고 활동적인 분위기','sharp active overall vibe',{mars:3,pluto:1}),c('dreamy','몽환적이고 섬세한 분위기','dreamy delicate overall vibe',{neptune:3,moon:1})],
 animal_type_primary:[c('cat','고양이상','cat-like visual metaphor',{mars:2,venus:1}),c('fox','여우상','fox-like visual metaphor',{mercury:2,uranus:1}),c('deer','사슴상','deer-like visual metaphor',{venus:2,neptune:1,jupiter:1}),c('dog','강아지상','dog-like visual metaphor',{sun:2,jupiter:1}),c('wolf','늑대상','wolf-like visual metaphor',{saturn:2,pluto:2}),c('rabbit','토끼상','rabbit-like visual metaphor',{moon:3}),c('bear','곰상','bear-like visual metaphor',{jupiter:2,moon:1})],
}
export const TRAIT_LABELS:Record<TraitKey,string>={age_impression:'연령감',relative_age:'상대적 나이 느낌',height_band:'키 느낌',body_build:'체형',proportions:'비율',face_shape_primary:'얼굴형',face_shape_secondary:'보조 윤곽',jaw:'턱선',eyes_shape:'눈매',eyes_size:'눈의 크기감',eye_impression:'시선',eyelid_style:'쌍꺼풀 연출',brows:'눈썹',nose_bridge:'콧대',nose_shape:'코 형태',mouth:'입매',smile:'미소',facial_softness:'볼과 윤곽',hair:'헤어',grooming:'손질',fashion:'스타일',first_impression:'첫인상',closer_impression:'가까이서의 분위기',overall_vibe:'전체 분위기',animal_type_primary:'동물상',animal_type_secondary:'보조 동물상'}
