import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync(new URL('../AppNext.tsx', import.meta.url), 'utf8')
const panel = readFileSync(new URL('../RelationshipInterpretationPanel.tsx', import.meta.url), 'utf8')
const personalPanel = readFileSync(new URL('../PersonalMarriagePanel.tsx', import.meta.url), 'utf8')
const cache = readFileSync(new URL('./readingCache.ts', import.meta.url), 'utf8')
const relationshipFn = readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/index.ts', import.meta.url), 'utf8')
const formatters = readFileSync(new URL('./resultFormatters.ts', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../../api/main.py', import.meta.url), 'utf8')
const personalEngine = readFileSync(new URL('../../../personal_marriage_v1.py', import.meta.url), 'utf8')

test('unmarried marriage splits no-counterpart forecast from specific-partner marriage compatibility', () => {
  assert.match(app, /marriageScope.*'personal'.*'partner'/s)
  assert.match(app, /상대 없음 · 개인 결혼운/)
  assert.match(app, /결혼 가능성 · 시기 · 미래 배우자상/)
  assert.match(app, /특정 상대 있음 · 결혼궁합/)
  assert.match(app, /const isPersonalMarriage/)
  assert.match(app, /const needsCounterpart/)
  assert.match(app, /\/v1\/marriage\/personal/)
  assert.match(app, /isPersonalMarriage\?runPersonalMarriage:runRelationship/)
  assert.match(app, /\{needsCounterpart&&<>/)
  assert.match(app, /setMarriageMode\('married'\);setMarriageScope\('partner'\)/)
  assert.doesNotMatch(personalPanel, /supabase\.functions\.invoke|GEMINI_API_KEY|generateContent/)
})

test('no-counterpart personal marriage actively provides fun probability timing and spouse archetype', () => {
  assert.match(api, /@app\.post\("\/v1\/marriage\/personal"\)/)
  assert.match(api, /counterpart_required["']:\s*False/)
  assert.match(personalEngine, /"counterpart_required": False/)
  assert.match(personalEngine, /"marriage_probability": True/)
  assert.match(personalEngine, /"spouse_archetype_prediction": True/)
  assert.match(personalEngine, /"specific_identity_claims": False/)
  assert.match(personalEngine, /marriage_probability_percent/)
  assert.match(personalEngine, /spouse_archetype/)
  assert.match(personalEngine, /appearance_hints/)
  assert.match(personalEngine, /career_clusters/)
  assert.match(personalEngine, /meeting_route/)
  assert.match(personalPanel, /결혼 가능성 지수/)
  assert.match(personalPanel, /외모 · 분위기/)
  assert.match(personalPanel, /직업 · 분야/)
  assert.match(personalPanel, /어디서 만날 가능성이 큰지/)
  assert.match(personalPanel, /0~100은 실제 통계 확률이 아니/)
})

test('relationship AI keeps compatibility reunion unmarried-partner and married semantics separate', () => {
  assert.match(relationshipFn, /type Purpose="compatibility"\|"reunion"\|"marriage_unmarried"\|"marriage_married"/)
  assert.match(relationshipFn, /수신\/발신\/재접점을 분리/)
  assert.match(relationshipFn, /특정 상대가 있는 미혼 결혼궁합/)
  assert.match(relationshipFn, /공식화될 가능성/)
  assert.match(relationshipFn, /프러포즈·약혼·결혼 결정/)
  assert.match(relationshipFn, /확정 사실처럼 단정하지/)
  assert.match(relationshipFn, /이미 결혼한 두 사람의 결혼생활 분석/)
  assert.match(relationshipFn, /결혼 가능성 표현은 금지/)
  assert.match(relationshipFn, /intimacy_resources/)
  assert.match(relationshipFn, /if\(!exact\)aspects=aspects\.filter/)
  assert.match(app, /analysisMode === 'reunion' && !reunionTiming/)
})

test('marriage UI makes marriage-specific reading primary and keeps generic compatibility evidence secondary', () => {
  assert.match(panel, /isMarriage&&ai\.data\.marriage_reading\?\.bottom_line/)
  assert.match(panel, /친밀감 · 공유자원/)
  assert.match(panel, /className="marriage-base-evidence"/)
  assert.match(panel, /<summary>기본 궁합 근거 보기<\/summary>/)
  assert.match(panel, /\{!isMarriage\?<><div className="relationship-ai-grid"/)
})

test('relationship AI has bounded paid calls cumulative usage server cache and rolling breaker', () => {
  assert.match(relationshipFn, /MAX_GEMINI_CALLS=2/)
  assert.match(relationshipFn, /MAX_PROMPT_BYTES=110000/)
  assert.match(relationshipFn, /addUsage\(firstUsage,second\.usage/)
  assert.match(relationshipFn, /attempt_count:calls/)
  assert.match(relationshipFn, /supabase-relationship-v11/)
  assert.match(relationshipFn, /server_cache:true/)
  assert.match(relationshipFn, /rolling_job_guard:true/)
  assert.match(relationshipFn, /cost_guard_blocked:true/)
  assert.match(relationshipFn, /ai_interpret_jobs/)
  assert.match(cache, /RELATIONSHIP_AI_CACHE_CONTRACT = 'relationship-v11\.6-reunion-compact-evidence'/)
  assert.match(cache, /contract: RELATIONSHIP_AI_CACHE_CONTRACT/)
})


test('external relationship prompt is compact bounded and clearly separated from raw full copy', () => {
  assert.match(formatters, /EXTERNAL_RELATIONSHIP_PROMPT_MAX_CHARS = 28000/)
  assert.match(formatters, /compactRelationshipExternalPacket/)
  assert.match(formatters, /for \(let level=0; level<=2; level\+\+\)/)
  assert.match(formatters, /prompt\.slice\(0,EXTERNAL_RELATIONSHIP_PROMPT_MAX_CHARS - 180\)/)
  assert.match(formatters, /좌표·원본 API 요청은 이미 계산에 반영됐으므로 외부 AI 입력에서는 중복 제거했다/)
  assert.match(app, /외부 AI용 압축 프롬프트/)
  assert.doesNotMatch(app, /handleCopy\('요청\/프롬프트 전체복사', relationshipPromptText/)
  assert.match(relationshipFn, /relationship-v11\.6-reunion-compact-evidence/)
})
