import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const server=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/index.ts',import.meta.url),'utf8')
const publicError=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/publicError.ts',import.meta.url),'utf8')
const panel=readFileSync(new URL('../RelationshipInterpretationPanel.tsx',import.meta.url),'utf8')
const hierarchyPanel=readFileSync(new URL('../ReunionHierarchyPanel.tsx',import.meta.url),'utf8')
const relationshipSummary=readFileSync(new URL('./relationshipUserSummary.ts',import.meta.url),'utf8')
const types=readFileSync(new URL('../appTypes.ts',import.meta.url),'utf8')
const reunionCss=readFileSync(new URL('../reunion-reading-product-v13.css',import.meta.url),'utf8')
const grounding=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/reunionGroundingV2.ts',import.meta.url),'utf8')

test('reunion v2 is reunion-only and preserves other relationship cache version',()=>{
  assert.match(server,/REUNION_VERSION="relationship-v12\.9-grounding-false-negative"/)
  assert.match(server,/versionForPurpose=\(purpose:Purpose\)=>purpose==="reunion"\?REUNION_VERSION:VERSION/)
  assert.match(server,/stable\(\{version:versionForPurpose\(purpose\),purpose,preferred,payload\}\)/)
})

test('server compiles question-first evidence and validates returned evidence refs',()=>{
  assert.match(server,/buildReunionEvidenceV2/)
  assert.match(server,/repairReunionGroundingV2/)
  assert.match(server,/const reunion_evidence_v2=buildReunionEvidenceV2\(base\)/)
  assert.match(server,/reunion_dimensions:base\.reunion_dimensions/)
  assert.match(server,/reunion_secondary_support:base\.reunion_secondary_support/)
  assert.match(server,/reunion_timing_windows:base\.reunion_timing_windows/)
  assert.match(server,/reunion_return_support:base\.reunion_return_support/)
  assert.match(server,/Solar Return\(태양회귀\)/)
  assert.match(server,/Lunar Return\(달회귀\)/)
  assert.match(server,/reunion_evidence_v2/)
  assert.match(server,/reunion_synthesis_v2:REUNION_V2_SCHEMA/)
  assert.match(server,/validEvidenceRefs/)
  assert.match(server,/refs\.some\(\(x:any\)=>!validEvidenceRefs\.has/)
  assert.match(publicError,/publicReunionV2/)
})

test('web prefers v2 question flow while retaining old reunion fallback',()=>{
  assert.match(types,/reunion_synthesis_v2\?:/)
  assert.match(panel,/const reunionV2/)
  assert.match(panel,/다시 연결될 여지가 있는 이유/)
  assert.match(panel,/누가 먼저 움직일 흐름인가/)
  assert.match(panel,/접점이 강해지는 시기/)
  assert.match(panel,/다시 붙었을 때 관계 구조/)
  assert.match(panel,/다시 깨뜨릴 수 있는 반복 패턴/)
  assert.match(panel,/reunion && reunionAi/)
})

test('reunion reading breaks long prose and exposes calculated day highlights',()=>{
  assert.match(panel,/function ReadableCopy/)
  assert.match(panel,/reunion-readable-copy/)
  assert.match(panel,/timing\.reconnection/)
  assert.match(panel,/timing\.incoming/)
  assert.match(panel,/timing\.outgoing/)
  assert.match(panel,/best_days/)
  assert.match(panel,/날짜로 좁혀 보면/)
  assert.match(panel,/연간·월간 배경/)
  assert.match(panel,/왜 이렇게 봤어\?/)
  assert.match(panel,/returnSupport/)
  assert.match(panel,/실제 연락·재회 확률이 아니라/)
  assert.match(reunionCss,/\.reunion-v2-window/)
  assert.match(reunionCss,/\.reunion-date-focus-list/)
})

test('reunion hierarchy puts full consultation answers before engine state',()=>{
  const cache=readFileSync(new URL('./readingCache.ts',import.meta.url),'utf8')
  const hierarchy=readFileSync(new URL('./reunionHierarchy.ts',import.meta.url),'utf8')
  assert.match(cache,/relationship-v12\.9-grounding-false-negative-v1/)
  const headings=['결론부터 보면','지금 두 사람의 흐름','실제 연락 가능성은?','누가 먼저 움직일지는?','왜 아직 서로를 신경 쓰기 쉬운가','언제가 중요한가','연락이 오면 무엇으로 진심을 구분하나','다시 만나도 반복되기 쉬운 문제','이번 리딩의 결론','계산된 흐름과 시기 자세히 보기','상대 → 나 / 나 → 상대 보조지표 보기','지난 시기 · 사후 확인용','계산 근거 보기']
  let cursor=-1
  for(const heading of headings){
    const next=hierarchyPanel.indexOf(heading)
    assert.ok(next>cursor,`${heading} order`)
    cursor=next
  }
  assert.match(hierarchyPanel,/실제 기록과 비교하는 개인 사후 확인용/)
  assert.match(hierarchyPanel,/과거와 맞아 보인다는 사실만으로 엔진 정확도가 증명되는 것은 아니야/)
  assert.match(hierarchyPanel,/이 값은 관계 자극의 방향이지 실제 속마음이나 선연락 행동을 관측한 값이 아니야/)
  assert.match(panel,/이전 계산 저장본/)
  assert.match(panel,/AI 해설 생성 없이도 지난 활성기 · 현재 흐름 · 앞으로의 후보 시기/)
  assert.match(panel,/이전 저장본 시기 해설 · 현재\/미래 판단용 아님/)
  assert.match(panel,/<ReunionHierarchyPanel/)
  assert.match(panel,/\(!reunion \|\| !hierarchyData\)/)
  assert.match(hierarchy,/top_periods: topPeriods/)
  assert.match(hierarchy,/past_windows: pastWindows/)
  assert.match(hierarchy,/current_windows: currentWindows/)
  assert.match(hierarchy,/slice\(0,3\)/)
  assert.match(hierarchy,/row\.date >= asOf/)
  assert.match(server,/날짜 문자열을 새로 만들거나/)
  assert.match(server,/이미 지난 날짜를 미래 핵심 시기처럼/)
  assert.match(server,/카르마적 인연/)
  assert.match(server,/summary는 첫 2~3문장 안에서 현재 가장 가까운 단계/)
  assert.match(server,/repeat_risks는 현재 단계와 직접 연결되는 근거가 있는 문제만 최대 2개/)
  assert.match(server,/counterpart_to_user=상대 진행차트가 사용자 출생차트를 자극하는 방향/)
  assert.match(server,/계산 근거 → 쉬운 뜻 → 실제 관계에서 나타날 수 있는 장면 → 함께 걸리는 반대\/제약 근거 → 종합/)
  assert.match(server,/applying은 앞으로 강해지는 배경/)
  assert.match(grounding,/카르마적 인연/)
})

test('reunion quality guard preserves narrative depth and keeps technical language out of the main consultation',()=>{
  assert.match(hierarchyPanel,/function phaseVerdict/)
  assert.match(hierarchyPanel,/function contactOutlook/)
  assert.match(hierarchyPanel,/function readerText/)
  assert.match(hierarchyPanel,/function normalizeReaderLanguage/)
  assert.match(hierarchyPanel,/function plainReaderSentence/)
  assert.match(hierarchyPanel,/MAIN_TECHNICAL_RE/)
  assert.match(hierarchyPanel,/READER_SCENE_START_RE/)
  assert.match(hierarchyPanel,/sentence\.slice\(index\)\.trim\(\)/)
  assert.match(hierarchyPanel,/!MAIN_TECHNICAL_RE\.test\(candidate\)/)
  assert.match(hierarchyPanel,/const summary = phaseVerdict\(hierarchyData\)/)
  assert.doesNotMatch(hierarchyPanel,/const summary = readerText\(reunionV2\?\.summary/)
  for (const marker of ['emotional_reactivation','contact_recontact','in_person_meeting','relationship_rebuilding','initiative_gate']) {
    assert.match(hierarchyPanel,new RegExp(`replace\\(/.*${marker}`))
  }
  assert.match(hierarchyPanel,/가장 먼저 눈여겨볼 흐름은/)
  assert.match(hierarchyPanel,/다음 단계/)
  assert.match(hierarchyPanel,/아직 뚜렷한 근거가 없어/)
  assert.match(hierarchyPanel,/두드러지는 시기/)
  assert.match(hierarchyPanel,/const grouped = new Map<string, ReunionPeriod\[\]>/)
  assert.match(hierarchyPanel,/같은 종류의 신호라 날짜마다 서로 다른 사건을 뜻하는 것은 아니야/)
  assert.match(hierarchyPanel,/function dedupeTimingWindows/)
  assert.doesNotMatch(hierarchyPanel,/function firstSentence/)
  assert.doesNotMatch(hierarchyPanel,/<p>\{verdict\}<\/p>/)
  assert.match(hierarchyPanel,/이 시기에는 관계 흐름의 변화를 눈여겨볼 수 있어/)
  assert.doesNotMatch(hierarchyPanel,/연락 가능성 자체는 열려 있어/)
  assert.match(hierarchyPanel,/실제 연락 가능성이 높다고 말할 근거는 아직 부족해/)
  assert.match(hierarchyPanel,/연락 여부를 다른 시기보다 더 눈여겨볼 수 있는 구간/)
  assert.match(hierarchyPanel,/현재 계산에서는 실제 연락이 가까워졌다고 볼 근거가 부족해/)
  assert.match(hierarchyPanel,/메시지가 실제로 온다고 확정할 수 있는 때는 아니야/)
  assert.match(hierarchyPanel,/안부·추억 이야기만 반복/)
  assert.match(hierarchyPanel,/구체적인 만남을 잡음/)
  assert.match(hierarchyPanel,/예전 문제와 앞으로의 관계를 피하지 않고 말함/)
  assert.match(hierarchyPanel,/말은 다정한데 행동이 이어지지 않음/)
  assert.match(hierarchyPanel,/const neutralDirectionRows = directionRows\.map/)
  assert.match(hierarchyPanel,/<ReadingDirections rows=\{neutralDirectionRows\}/)
  assert.match(hierarchyPanel,/<details className="reading-more reunion-retrospective">/)
  assert.match(hierarchyPanel,/<details className="reading-more reunion-contact-is-not-reunion">/)
  assert.doesNotMatch(hierarchyPanel,/감정 활성과 연락 단계는 운의 흐름이 열려/)
  assert.doesNotMatch(hierarchyPanel,/단계가 현재 창에 걸려 있어/)
  assert.doesNotMatch(hierarchyPanel,/현재 열린 단계보다 뒤의 일을 한꺼번에 재회로 묶어 읽지 않아/)
  assert.doesNotMatch(hierarchyPanel,/const STAGE_COPY/)
})

test('reunion grounding deduplicates locally and closes initiative claims across section and summary',()=>{
  assert.match(grounding,/function localText/)
  assert.match(grounding,/function sectionPair/)
  assert.match(grounding,/const why = sectionPair/)
  assert.match(grounding,/const initiative = sectionPair/)
  assert.doesNotMatch(grounding,/const state: DedupState = \{ sentences: new Set\(\), evidence: new Set\(\) \}\n  const whyConclusion/)
  assert.match(grounding,/replace\(\/용수자리\/g, '진북교점'\)/)
  assert.match(grounding,/누가 먼저 연락할지는 현재 계산만으로 정하기 어렵다/)
  assert.match(grounding,/실제 만남을 잡는지/)
  assert.match(grounding,/시작\\s\*압력/)
  assert.match(grounding,/v2\.summary = safeInitiativeDetail\(v2\?\.summary, provisional\)/)
})

test('legacy calculated reunion fallback never turns directional activation into first-contact prediction',()=>{
  assert.match(relationshipSummary,/상대 → 나 방향의 관계 자극이 비교적 강하게 잡혀 있어/)
  assert.match(relationshipSummary,/나 → 상대 방향의 관계 자극이 비교적 강하게 잡혀 있어/)
  assert.match(relationshipSummary,/과거 인연 재접점 지표는 강한 편이야/)
  assert.match(relationshipSummary,/상대 → 나 관계 자극이 상대적으로 두드러지는 때/)
  assert.match(relationshipSummary,/나 → 상대 관계 자극이 상대적으로 두드러지는 때/)
  for(const legacy of ['상대가 먼저 연락할 흐름은 약한 편이야','내가 먼저 짧게 말을 꺼내기 좋은 편이야','재접촉의 움직임은 살아 있어','다시 대화할 여지는 열려 있지만']) {
    assert.equal(relationshipSummary.includes(legacy),false,`legacy directional copy must stay removed: ${legacy}`)
  }
})

test('all relationship modes keep distinct decision questions instead of one swapped-name template',()=>{
  for(const marker of ['궁합 전체 해설','결혼궁합 전체 해설','결혼생활 전체 해설','재회 흐름 전체 해설']) assert.match(panel,new RegExp(marker))
  assert.match(relationshipSummary,/함께 쓰는 돈, 집안일, 돌봄, 애정 표현, 혼자 쉬는 시간/)
  assert.match(relationshipSummary,/같은 다툼이 시작되는 말과 시간을 함께 적어봐/)
  assert.match(relationshipSummary,/이전에 대화가 끊긴 문제를 한 가지씩/)
  assert.match(relationshipSummary,/편안한 연락 빈도와 함께 보내고 싶은 시간을 서로 맞춰봐/)
  assert.match(panel,/생활비, 집안일, 가족 관계, 혼자 쉴 시간/)
  assert.match(panel,/오래 함께했다는 사실과 지금 편안하게 유지되고 있다는 건 같은 뜻이 아니야/)
  assert.match(panel,/연락이 다시 닿았다는 사실만으로 재결합이나 관계 회복이 확정됐다고 읽지는 마/)
})

test('archive filter guards iOS date controls from widening the page',()=>{
  assert.match(reunionCss,/\.archive-filter-grid input\[type='date'\]/)
  assert.match(reunionCss,/max-inline-size:\s*100%\s*!important/)
  assert.match(reunionCss,/@media \(max-width: 480px\)/)
  assert.match(reunionCss,/\.archive-filter-grid\s*\{\s*grid-template-columns:\s*minmax\(0, 1fr\)\s*!important/)
})
