import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync(new URL('../AppNext.tsx', import.meta.url), 'utf8')
const panel = readFileSync(new URL('../RelationshipInterpretationPanel.tsx', import.meta.url), 'utf8')
const personalPanel = readFileSync(new URL('../PersonalMarriagePanel.tsx', import.meta.url), 'utf8')
const cache = readFileSync(new URL('./readingCache.ts', import.meta.url), 'utf8')
const relationshipFn = readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/index.ts', import.meta.url), 'utf8')
const formatters = readFileSync(new URL('./resultFormatters.ts', import.meta.url), 'utf8')
const relationshipSummary = readFileSync(new URL('./relationshipUserSummary.ts', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../../api/main.py', import.meta.url), 'utf8')
const personalEngine = readFileSync(new URL('../../../personal_marriage_v1.py', import.meta.url), 'utf8')

test('unmarried marriage splits no-counterpart forecast from specific-partner marriage compatibility', () => {
  assert.match(app, /marriageScope.*'personal'.*'partner'/s)
  assert.match(app, /상대 없음 · 개인 결혼운/)
  assert.match(app, /결혼 가능성 · 시기 · 미래 배우자상/)
  assert.match(app, /특정 상대 있음 · 결혼궁합/)
  assert.match(app, /const isPersonalMarriage/)
  assert.match(app, /const needsCounterpart/)
  assert.match(app, /\/v1\/marriage\/personal/)
  assert.match(app, /isPersonalMarriage\?runPersonalMarriage:runRelationship/)
  assert.match(app, /\{needsCounterpart&&<>/)
  assert.match(app, /setMarriageMode\('married'\);setMarriageScope\('partner'\)/)
  assert.doesNotMatch(personalPanel, /supabase\.functions\.invoke|GEMINI_API_KEY|generateContent/)
})

test('personal marriage preserves computed data with non-prophetic creative presentation', () => {
  assert.match(api, /@app\.post\("\/v1\/marriage\/personal"\)/)
  assert.match(api, /counterpart_required["']:\s*False/)
  assert.match(personalEngine, /"counterpart_required": False/)
  assert.match(personalEngine, /"marriage_probability": True/)
  assert.match(personalEngine, /"spouse_archetype_prediction": True/)
  assert.match(personalEngine, /"specific_identity_claims": False/)
  assert.match(personalEngine, /marriage_probability_percent/)
  assert.match(personalEngine, /spouse_archetype/)
  assert.match(personalEngine, /appearance_hints/)
  assert.match(personalEngine, /career_clusters/)
  assert.match(personalEngine, /meeting_route/)
  assert.match(personalPanel, /forecast\.marriage_probability_percent/)
  assert.match(personalPanel, /나의 취향을 그려본다면/)
  assert.match(personalPanel, /spouse\.appearance_hints/)
  assert.match(personalPanel, /JSON\.stringify\(result, null, 2\)/)
  assert.match(personalPanel, /통계 확률 아님/)
  assert.match(personalPanel, /기술 근거 자세히 보기/)
  assert.match(personalPanel, /AI 초상 콘셉트 프롬프트 복사/)
})

test('relationship AI keeps compatibility reunion unmarried-partner and married semantics separate', () => {
  assert.match(relationshipFn, /type Purpose="compatibility"\|"reunion"\|"marriage_unmarried"\|"marriage_married"/)
  assert.match(relationshipFn, /CALCULATED_DATA\.reunion_evidence_v2/)
  assert.match(relationshipFn, /reunion_dimensions:base\.reunion_dimensions/)
  assert.match(relationshipFn, /reunion_timing_windows:base\.reunion_timing_windows/)
  assert.match(relationshipFn, /reunion_secondary_support:base\.reunion_secondary_support/)
  assert.match(relationshipFn, /initiative_gate/)
  assert.match(relationshipFn, /감정 활성 \/ 연락·재접촉 \/ 실제 만남 \/ 관계 재결합/)
  assert.match(relationshipFn, /왜 다시 연결될 여지가 있는가/)
  assert.match(relationshipFn, /같은 파생계열 반복은 수렴 근거로 세지 않는다/)
  assert.match(relationshipFn, /reunion_synthesis_v2:REUNION_V2_SCHEMA/)
  assert.match(relationshipFn, /특정 상대가 있는 미혼 결혼궁합/)
  assert.match(relationshipFn, /공식화될 가능성/)
  assert.match(relationshipFn, /프러포즈·약혼·결혼 결정/)
  assert.match(relationshipFn, /확정 사실처럼 단정하지/)
  assert.match(relationshipFn, /이미 결혼한 두 사람의 결혼생활 분석/)
  assert.match(relationshipFn, /결혼 가능성 표현은 금지/)
  assert.match(relationshipFn, /intimacy_resources/)
  assert.match(relationshipFn, /if\(!available\)aspects=aspects\.filter/)
  assert.match(relationshipFn, /누락하거나 제외하지 말고 전부 분석한다/)
  assert.match(app, /analysisMode === 'reunion' && !reunionTiming/)
})

test('marriage UI uses mode-specific deterministic view and preserves validated enrichment', () => {
  assert.match(panel, /buildRelationshipUserSummary/)
  assert.match(panel, /data-mode=\{analysisMode\}/)
  assert.match(panel, /analysisMode\.startsWith\('marriage_'\)/)
  assert.match(panel, /ai\.data\.marriage_reading\?\.bottom_line/)
  assert.match(panel, /<summary>기술 근거 자세히 보기<\/summary>/)
  assert.match(panel, /JSON\.stringify\(ai\.data/)
})

test('compatibility and both marriage modes prioritize different real-life questions', () => {
  assert.match(relationshipSummary, /const sectionOrder: Role\[\] = married/)
  assert.match(relationshipSummary, /\['communication','stability','attraction','power','perspective'\]/)
  assert.match(relationshipSummary, /\['stability','communication','attraction','power','perspective'\]/)
  assert.match(relationshipSummary, /반복 갈등 · 회복 방식/)
  assert.match(relationshipSummary, /생활 책임 · 돌봄 분담/)
  assert.match(relationshipSummary, /생활비 · 집안일 · 책임/)
  assert.match(relationshipSummary, /결정권 · 가족 경계/)
  assert.match(relationshipSummary, /결혼 전 합의할 것/)
  assert.match(relationshipSummary, /이번에 함께 바꿀 것/)
  assert.match(relationshipSummary, /생활비·집안일·돌봄·가족행사·혼자 쉴 시간/)
  assert.match(relationshipSummary, /말이 꼬였을 때 서로 뜻을 확인하고 다시 대화를 이어갈 수 있는지가 핵심/)
  assert.match(panel, /index<2/)
})

test('relationship modes keep Gemini natural language primary and deterministic prose as fallback', () => {
  assert.match(panel, /relationship-natural-reading/)
  assert.match(panel, /Gemini 자연어 해설/)
  assert.match(panel, /relationship-calculated-fallback/)
  assert.ok(panel.indexOf('relationship-natural-reading') < panel.indexOf('relationship-calculated-fallback'))
})

test('relationship AI has bounded paid calls cumulative usage server cache and rolling breaker', () => {
  assert.match(relationshipFn, /MAX_GEMINI_CALLS=2/)
  assert.match(relationshipFn, /MAX_PROMPT_BYTES=180000,REUNION_PROMPT_TARGET_BYTES=85000,MAX_AI_JOB_ESTIMATED_KRW=300/)
  assert.match(relationshipFn, /addUsage\(firstUsage,second\.usage/)
  assert.match(relationshipFn, /attempt_count:calls/)
  assert.match(relationshipFn, /supabase-relationship-v11/)
  assert.match(readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/publicError.ts', import.meta.url),'utf8'), /server_cache:true/)
  assert.match(relationshipFn, /rolling_job_guard:true/)
  assert.match(relationshipFn, /cost_guard_blocked:true/)
  assert.match(relationshipFn, /ai_interpret_jobs/)
  assert.match(cache, /RELATIONSHIP_AI_CACHE_CONTRACT = 'relationship-v11\.8-provisional-time-reference'/)
  assert.match(cache, /RELATIONSHIP_REUNION_AI_CACHE_CONTRACT = 'relationship-v12\.9-grounding-false-negative-v1-consultation-depth-v3'/)
  assert.match(cache, /purpose === 'reunion' \? RELATIONSHIP_REUNION_AI_CACHE_CONTRACT : RELATIONSHIP_AI_CACHE_CONTRACT/)
})

test('external relationship prompt is compact bounded and clearly separated from raw full copy', () => {
  assert.match(formatters, /EXTERNAL_RELATIONSHIP_PROMPT_MAX_CHARS = 28000/)
  assert.match(formatters, /compactRelationshipExternalPacket/)
  assert.match(formatters, /for \(let level=0; level<=2; level\+\+\)/)
  assert.match(formatters, /prompt\.slice\(0,EXTERNAL_RELATIONSHIP_PROMPT_MAX_CHARS - 180\)/)
  assert.match(formatters, /좌표·원본 API 요청은 이미 계산에 반영됐으므로 외부 AI 입력에서는 중복 제거했다/)
  assert.match(app, /ExternalPromptCopy onCopy={mode=>.*relationshipPromptText/)
  assert.doesNotMatch(app, /handleCopy\('요청\/프롬프트 전체복사', relationshipPromptText/)
  assert.match(relationshipFn, /relationship-v11\.8-provisional-time-reference/)
  assert.match(relationshipFn, /relationship-v12\.9-grounding-false-negative/)
})

// Run the executable browser boundary suite through the existing CI entrypoint.
import './relationshipAiPublicError.test.mjs'