import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const server=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/index.ts',import.meta.url),'utf8')
const publicError=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/publicError.ts',import.meta.url),'utf8')
const panel=readFileSync(new URL('../RelationshipInterpretationPanel.tsx',import.meta.url),'utf8')
const types=readFileSync(new URL('../appTypes.ts',import.meta.url),'utf8')
const reunionCss=readFileSync(new URL('../reunion-reading-product-v13.css',import.meta.url),'utf8')

test('reunion v2 is reunion-only and preserves other relationship cache version',()=>{
  assert.match(server,/REUNION_VERSION="relationship-v12\.4-stage-grounded-narrative"/)
  assert.match(server,/versionForPurpose=\(purpose:Purpose\)=>purpose==="reunion"\?REUNION_VERSION:VERSION/)
  assert.match(server,/stable\(\{version:versionForPurpose\(purpose\),purpose,preferred,payload\}\)/)
})

test('server compiles question-first evidence and validates returned evidence refs',()=>{
  assert.match(server,/buildReunionEvidenceV2/)
  assert.match(server,/repairReunionGroundingV2/)
  assert.match(server,/const reunion_evidence_v2=buildReunionEvidenceV2\(base\)/)
  assert.match(server,/reunion_dimensions:base\.reunion_dimensions/)
  assert.match(server,/reunion_secondary_support:base\.reunion_secondary_support/)
  assert.match(server,/reunion_timing_windows:base\.reunion_timing_windows/)
  assert.match(server,/reunion_return_support:base\.reunion_return_support/)
  assert.match(server,/Solar Return\(태양회귀\)/)
  assert.match(server,/Lunar Return\(달회귀\)/)
  assert.match(server,/reunion_evidence_v2/)
  assert.match(server,/reunion_synthesis_v2:REUNION_V2_SCHEMA/)
  assert.match(server,/validEvidenceRefs/)
  assert.match(server,/refs\.some\(\(x:any\)=>!validEvidenceRefs\.has/)
  assert.match(publicError,/publicReunionV2/)
})

test('web prefers v2 question flow while retaining old reunion fallback',()=>{
  assert.match(types,/reunion_synthesis_v2\?:/)
  assert.match(panel,/const reunionV2/)
  assert.match(panel,/다시 연결될 여지가 있는 이유/)
  assert.match(panel,/누가 먼저 움직일 흐름인가/)
  assert.match(panel,/접점이 강해지는 시기/)
  assert.match(panel,/다시 붙었을 때 관계 구조/)
  assert.match(panel,/다시 깨뜨릴 수 있는 반복 패턴/)
  assert.match(panel,/reunion && reunionAi/)
})

test('reunion reading breaks long prose and exposes calculated day highlights',()=>{
  assert.match(panel,/function ReadableCopy/)
  assert.match(panel,/reunion-readable-copy/)
  assert.match(panel,/timing\.reconnection/)
  assert.match(panel,/timing\.incoming/)
  assert.match(panel,/timing\.outgoing/)
  assert.match(panel,/best_days/)
  assert.match(panel,/날짜로 좁혀 보면/)
  assert.match(panel,/연간·월간 배경/)
  assert.match(panel,/왜 이렇게 봤어\?/)
  assert.match(panel,/returnSupport/)
  assert.match(panel,/실제 연락·재회 확률이 아니라/)
  assert.match(reunionCss,/\.reunion-v2-window/)
  assert.match(reunionCss,/\.reunion-date-focus-list/)
})

test('reunion v2.14 keeps hierarchy timing deterministic while expanding stage-grounded narrative',()=>{
  const cache=readFileSync(new URL('./readingCache.ts',import.meta.url),'utf8')
  const hierarchy=readFileSync(new URL('./reunionHierarchy.ts',import.meta.url),'utf8')
  const grounding=readFileSync(new URL('../../../supabase/functions/relationship-interpret-v9-preview/reunionGroundingV2.ts',import.meta.url),'utf8')
  assert.match(cache,/relationship-v12\.4-stage-grounded-narrative-v1/)
  assert.match(panel,/재회운 핵심/)
  assert.match(panel,/가장 가까운 활성창/)
  assert.match(panel,/지난 활성기 · 사후검증/)
  assert.match(panel,/이전 계산 저장본/)
  assert.match(panel,/AI 해설 생성 없이도 지난 활성기 · 현재 흐름 · 앞으로의 후보 시기/)
  assert.match(panel,/이전 저장본 시기 해설 · 현재\/미래 판단용 아님/)
  assert.match(panel,/현재 흐름/)
  assert.match(panel,/앞으로의 후보 시기/)
  assert.match(panel,/연락 ≠ 재회/)
  assert.match(panel,/재구축 조건/)
  assert.match(panel,/근거 보기 · 계산\/정밀도/)
  assert.match(panel,/실제 메시지·답장·만남·관계 변화 기록과 비교하는 개인 사후 확인용/)
  assert.match(panel,/연락 한 번이나 답장 하나만으로 재회를 판정하지 않아/)
  assert.match(panel,/hidden=\{reunion && !!hierarchyData\}/)
  assert.match(panel,/앞으로의 후보 시기/)
  assert.match(panel,/reunionStageHuman/)
  assert.match(panel,/보조지표 활성도/)
  assert.match(panel,/\(!reunion \|\| !hierarchyData\)/)
  assert.match(hierarchy,/top_periods: topPeriods/)
  assert.match(hierarchy,/past_windows: pastWindows/)
  assert.match(hierarchy,/current_windows: currentWindows/)
  assert.match(hierarchy,/slice\(0,3\)/)
  assert.match(hierarchy,/row\.date >= asOf/)
  assert.match(server,/날짜 문자열을 새로 만들거나/)
  assert.match(server,/이미 지난 날짜를 미래 핵심 시기처럼/)
  assert.match(server,/카르마적 인연/)
  assert.match(server,/summary는 첫 2~3문장 안에서 현재 가장 가까운 단계/)
  assert.match(server,/repeat_risks는 현재 단계와 직접 연결되는 근거가 있는 문제만 최대 2개/)
  assert.match(grounding,/카르마적 인연/)
})

test('archive filter guards iOS date controls from widening the page',()=>{
  assert.match(reunionCss,/\.archive-filter-grid input\[type='date'\]/)
  assert.match(reunionCss,/max-inline-size:\s*100%\s*!important/)
  assert.match(reunionCss,/@media \(max-width: 480px\)/)
  assert.match(reunionCss,/\.archive-filter-grid\s*\{\s*grid-template-columns:\s*minmax\(0, 1fr\)\s*!important/)
})
