from pathlib import Path
p=Path('supabase/functions/relationship-interpret-v9-preview/index.ts')
t=p.read_text(encoding='utf-8')
t=t.replace('VERSION="relationship-v10-compat-marriage-depth"','VERSION="relationship-v10.1-grounded-depth"')
needle="- 서양점성술과 사주는 독립 근거로 읽고, 둘이 같은 주제를 가리킬 때만 '교차해서 보면'이라고 종합한다.\n- 일반론 조언 금지. 실제 접점과 연결된 반복 장면·관계 역학을 설명한다."
replacement="- 서양점성술과 사주는 독립 근거로 읽고, 둘이 같은 주제를 가리킬 때만 '교차해서 보면'이라고 종합한다.\n- 사주는 CALCULATED_DATA.saju_relationship에 실제로 들어온 원주·day_master_relation(일간 상호관계·십성)·spouse_palace(일지·배우자궁 합충해파)·cross_branch_links(교차 지지관계)만 사용한다. 데이터에 없는 天干合(천간합: 갑기합·을경합·병신합·정임합·무계합), 신강·신약, 용신·희신·기신, 배우자성, 합혼점수, 도화/홍염은 절대 만들지 않는다.\n- 일반론 조언 금지. 실제 접점과 연결된 반복 장면·관계 역학을 설명한다."
if needle not in t: raise SystemExit('system marker missing')
t=t.replace(needle,replacement,1)
t=t.replace('marriage_reading 각 항목은 4~7문장으로 쓴다. 결속이 강해도 생활궁합이 힘들 수 있고, 끌림이 강해도 책임 구조가 약할 수 있음을 분리한다.','marriage_reading의 bottom_line/bond/emotional_home/daily_life/conflict_repair/commitment_or_current_cycle/timing/caution을 각각 최소 4문장 수준으로 충분히 쓴다. 결속이 강해도 생활궁합이 힘들 수 있고, 끌림이 강해도 책임 구조가 약할 수 있음을 분리한다.')
validate_end='''function validate(o:any,p:Purpose){if(!o||typeof o!=="object")return null;const rr=o.reunion_reading??{},mr=o.marriage_reading??{};const out:any={headline:cut(o.headline,450),overview:cut(o.overview,6500),chemistry:cut(o.chemistry,4200),emotional_dynamic:cut(o.emotional_dynamic,4200),communication:cut(o.communication,4200),conflict_pattern:cut(o.conflict_pattern,4200),power_boundaries:cut(o.power_boundaries,3800),long_term:cut(o.long_term,4500),timing:cut(o.timing,3500),reunion_context:cut(o.reunion_context,3500),felt_scenarios:Array.isArray(o.felt_scenarios)?o.felt_scenarios.slice(0,4).map((x:any)=>cut(x,1300)):[],reunion_reading:{bottom_line:cut(rr.bottom_line,4500),incoming_contact:cut(rr.incoming_contact,4000),outgoing_contact:cut(rr.outgoing_contact,3500),reconnection_windows:cut(rr.reconnection_windows,6000),low_windows:cut(rr.low_windows,3500),relationship_filter:cut(rr.relationship_filter,4500),precision_note:cut(rr.precision_note,1800)},marriage_reading:{mode:cut(mr.mode,80),bottom_line:cut(mr.bottom_line,4800),bond:cut(mr.bond,4200),emotional_home:cut(mr.emotional_home,4200),daily_life:cut(mr.daily_life,4800),conflict_repair:cut(mr.conflict_repair,4200),commitment_or_current_cycle:cut(mr.commitment_or_current_cycle,4200),timing:cut(mr.timing,3800),caution:cut(mr.caution,3800),precision_note:cut(mr.precision_note,1800)},practical_advice:Array.isArray(o.practical_advice)?o.practical_advice.slice(0,4).map((x:any)=>cut(x,1200)):[],top_aspects:Array.isArray(o.top_aspects)?o.top_aspects.slice(0,10).map((x:any)=>({label:cut(x?.label,500),meaning:cut(x?.meaning,1800)})):[],limits:cut(o.limits,2200)};if(p!=="reunion")out.reunion_reading={bottom_line:"",incoming_contact:"",outgoing_contact:"",reconnection_windows:"",low_windows:"",relationship_filter:"",precision_note:""};if(!p.startsWith("marriage_"))out.marriage_reading={mode:"",bottom_line:"",bond:"",emotional_home:"",daily_life:"",conflict_repair:"",commitment_or_current_cycle:"",timing:"",caution:"",precision_note:""};return deep(out);}'''
if validate_end not in t: raise SystemExit('validate marker missing')
grounded='''\nfunction grounded(data:any,payload:any,p:Purpose){const all=JSON.stringify(data);const src=JSON.stringify(payload);const forbidden=["갑기합","을경합","병신합","정임합","무계합","신강","신약","용신","희신","기신","배우자성","합혼점수"];for(const word of forbidden)if(all.includes(word)&&!src.includes(word))return false;if(p==="compatibility"){if(data.overview.length<350)return false;for(const k of ["chemistry","emotional_dynamic","communication","conflict_pattern","power_boundaries","long_term"])if(String(data[k]??"").length<120)return false;if((data.felt_scenarios??[]).length<3)return false;}if(p.startsWith("marriage_")){const m=data.marriage_reading??{};if(data.overview.length<300)return false;if(String(m.bottom_line??"").length<260)return false;for(const k of ["bond","emotional_home","daily_life","conflict_repair","commitment_or_current_cycle","timing","caution"])if(String(m[k]??"").length<170)return false;}if(p==="reunion"&&String(data.reunion_reading?.bottom_line??"").length<220)return false;return true;}'''
t=t.replace(validate_end,validate_end+grounded,1)
old='''try{const data=validate(JSON.parse(txt),purpose);if(!data)return {ok:false,error:"관계 해설 구조 검증 실패",model};const min=purpose==="compatibility"?350:purpose.startsWith("marriage_")?300:220;if(data.overview.length<min)return {ok:false,error:"관계 해설이 지나치게 짧았어",model};return {ok:true,data,model,interpreter_version:VERSION};}'''
new='''try{const data=validate(JSON.parse(txt),purpose);if(!data||!grounded(data,payload,purpose))return {ok:false,error:"관계 해설이 깊이/근거 검증을 통과하지 못했어",model};return {ok:true,data,model,interpreter_version:VERSION};}'''
if old not in t: raise SystemExit('generate validation marker missing')
t=t.replace(old,new,1)
t=t.replace('temperature:.38','temperature:.32')
t=t.replace('"결혼운이다. 연애궁합과 달리 가정·생활·책임·공유재정·친밀감·갈등회복을 중심으로 깊게 써라."','"결혼운이다. 가정·생활·책임·공유재정·친밀감·갈등회복을 중심으로 각 항목을 최소 4문장으로 써라."')
t=t.replace('"구조 오류 재시도다. JSON 완결성을 위해 중복 표현만 줄이고 근거·오브·시기·사주 포인트는 유지해라."','"재시도다. 완전한 JSON을 만들되 근거·오브·사주 허용필드·시기는 유지하고 중복만 줄여라."')
t=t.replace('관계 해설을 완전한 구조로 생성하지 못했어.','관계 해설을 완전한 구조와 계산 근거로 생성하지 못했어.')
p.write_text(t,encoding='utf-8')
print('relationship AI source synced to v10.1')
