import assert from 'node:assert/strict'
import test from 'node:test'
import { precisionGateFromPayload, sanitizeProvisionalCalculation, auditProvisionalResidue, attachPrecisionPacketMetadata, sanitizeProvisionalInterpretationOutput } from './precisionV2.ts'

const exact={contract_version:'integrated-precision-v2',time_available:true,time_exact:true,status:'exact',time_source:'official_record',time_confidence:'exact',scoring_mode:'full_exact',allow_natal_moon_scoring:true,allow_angles_houses_scoring:true,allow_house_ruler_bonus:true,allow_intraday_timing:true,allow_saju_ai:true,allow_thai_ai:true,layer_policy:{natal_moon:'allow',angles_houses:'allow',house_ruler_bonus:'allow',intraday_timing:'allow',saju_ai:'allow',thai_ai:'allow'}}
const provisional={contract_version:'integrated-precision-v2',time_available:true,time_exact:false,status:'provisional',time_source:'family_memory',time_confidence:'medium',scoring_mode:'planet_only_provisional',allow_natal_moon_scoring:false,allow_angles_houses_scoring:false,allow_house_ruler_bonus:false,allow_intraday_timing:false,allow_saju_ai:false,allow_thai_ai:false,layer_policy:{natal_moon:'exclude',angles_houses:'exclude',house_ruler_bonus:'exclude',intraday_timing:'exclude',saju_ai:'exclude',thai_ai:'exclude'}}

test('classifies exact and provisional',()=>{assert.equal(precisionGateFromPayload({precision:exact}).mode,'exact');assert.equal(precisionGateFromPayload({precision:provisional}).mode,'provisional')})
test('rejects legacy and inconsistent provenance',()=>{assert.equal(precisionGateFromPayload({}).ok,false);assert.equal(precisionGateFromPayload({precision:{...exact,time_source:'family_memory'}}).ok,false)})
test('provisional sanitizer removes mixed-system and time-sensitive evidence',()=>{const c={precision:provisional,saju:{pillars:{}},thai:{x:1},western:{natal:{asc:1,mc:2,house_system:{used:'Placidus'}},detail_days:[{x:1}],daily_scores:[{evidence:[{kind:'aspect',transit:'Moon',target:'Venus',text:'Moon→Venus trine'},{kind:'aspect',transit:'Venus',target:'Moon',text:'Venus→Moon trine'},{kind:'house',whole_house:7,text:'Venus · Whole Sign 7H'}]}]}};const safe=sanitizeProvisionalCalculation(c);assert.equal(safe.saju.provisional_excluded_from_ai,true);assert.equal(safe.thai.provisional_excluded_from_ai,true);assert.equal(safe.western.daily_scores[0].evidence.length,1);assert.equal(safe.western.daily_scores[0].evidence[0].target,'Venus');assert.equal(auditProvisionalResidue(safe).ok,true)})
test('residue audit catches time and house leaks',()=>{assert.equal(auditProvisionalResidue({x:'Placidus 7H 12:30'}).ok,false);assert.equal(auditProvisionalResidue({target:'MC'}).ok,false)})
test('packet metadata is Western-only in provisional',()=>{const p=attachPrecisionPacketMetadata({saju:{x:1},thai:{x:1},evidence_ledger:[{ref:'W:window:1'},{ref:'W:planet:1'}]},{precision:provisional});assert.equal(p.precision_mode,'provisional');assert.equal(p.saju,null);assert.equal(p.thai,null);assert.deepEqual(p.evidence_ledger,[{ref:'W:planet:1'}])})
test('final provisional output strips cross-system claims',()=>{const out=sanitizeProvisionalInterpretationOutput({overall:{summary:'Western flow. Thai says X.',dominant_pattern:'사주 흐름. stable.'},systems:{western:'ok',saju:'bad',thai:'bad'},cross_checks:[{mode:'복수체계',saju:'x',thai:'y',synthesis:'Thai match'}]});assert.equal(out.systems.saju,'');assert.equal(out.systems.thai,'');assert.equal(out.cross_checks[0].mode,'Western단독');assert.doesNotMatch(out.overall.summary,/Thai/)})
test('transit Moon to robust natal planet remains allowed',()=>{assert.equal(auditProvisionalResidue({evidence:[{kind:'aspect',transit:'Moon',target:'Venus',text:'Moon→Venus trine'}]}).ok,true)})
