import { useState } from 'react'
import type { IntegratedApiResponse } from './appTypes'
import { datingCelebrityReference,defaultDatingPartnerGender,buildDatingArchetype,datingPortraitPrompt,type PortraitOptions } from './lib/datingArchetype'
export function DatingArchetypePanel({calculation,profileGender}:{calculation:IntegratedApiResponse;profileGender?:unknown}) {
 const view=buildDatingArchetype(calculation)
 const [options,setOptions]=useState<PortraitOptions>({gender:defaultDatingPartnerGender(profileGender),style:'real',frame:'half',outfit:'meeting'})
 const [status,setStatus]=useState('')
 async function copy(language:'ko'|'en'){try{await navigator.clipboard.writeText(datingPortraitPrompt(options,language,view.style));setStatus('초상 프롬프트 복사 완료')}catch{setStatus('복사 권한을 사용할 수 없어.')}}
 return <section className="system-lens dating-archetype"><h3>{view.title} <span className="reading-badge signal-reconnection">FUN</span></h3><label>상대 성별<select aria-label="상대 성별" value={options.gender} onChange={e=>setOptions({...options,gender:e.target.value as PortraitOptions['gender']})}><option value="male">남성</option><option value="female">여성</option><option value="neutral">지정하지 않음</option></select></label><p>{view.summary}</p><small>{view.precision}</small>{view.visual&&<><p>{view.visualPolicy}</p><dl className="dating-visual-grid">{Object.entries({전체분위기:view.visual.mood,키: view.precision.includes('제한')?'생시 제한 · 키 연출 생략':view.visual.height,체형:view.precision.includes('제한')?'생시 제한 · 체형 연출 생략':view.visual.body,얼굴형:view.visual.face,눈매:view.visual.eyes,코:view.visual.nose,입매:view.visual.mouth,헤어:view.visual.hair,스타일:view.visual.fashion,첫인상:view.visual.first,가까워졌을때:view.visual.closer,동물상:view.visual.animal}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h4>매력 포인트 · 창작 연출</h4><p>{view.visual.attractions.join(' / ')}</p><details><summary>연예인 느낌 · FUN</summary><p>{view.style && datingCelebrityReference(view.style,options.gender)}</p><p>미소·분위기·스타일만 참고하는 예시야. 외모 전체나 매력의 정도가 같다는 뜻은 아니야. 이름은 이미지 프롬프트에 넣지 않아.</p></details></>}<details><summary>외형 해석 범위</summary><p>{view.fields.join(' · ')}: 현재 엔진에 외형 변환 규칙이 없어 값이나 인물을 추정하지 않았어.</p></details><details className="portrait-concept"><summary>이 사람 느낌을 이미지로 보기</summary><p>아래는 사용자가 고르는 창작 연출이야. 다음에 만날 사람의 외모 설명과는 달라.</p><label>화풍<select value={options.style} onChange={e=>setOptions({...options,style:e.target.value as PortraitOptions['style']})}><option value="real">자연스러운 일상 실사</option><option value="dream">몽환적 실사</option><option value="illustration">일러스트</option></select></label><label>구도<select value={options.frame} onChange={e=>setOptions({...options,frame:e.target.value as PortraitOptions['frame']})}><option value="face">얼굴 중심</option><option value="half">상반신</option><option value="full">전신</option></select></label><label>스타일<select value={options.outfit} onChange={e=>setOptions({...options,outfit:e.target.value as PortraitOptions['outfit']})}><option value="daily">데일리</option><option value="date">데이트룩</option><option value="meeting">첫 만남 분위기</option></select></label><p>{datingPortraitPrompt(options,'ko',view.style)}</p><div className="system-context-chips"><button type="button" onClick={()=>copy('ko')}>한국어 초상 프롬프트 복사</button><button type="button" onClick={()=>copy('en')}>English Prompt Copy</button></div><p role="status">{status}</p></details><p className="reading-safety-note">{view.limit}</p></section>
}
